In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import model_selection, ensemble, preprocessing, metrics, svm, cluster
from sklearn.metrics import roc_auc_score
import warnings
import xgboost as xgb
from xgboost.sklearn import XGBClassifier
warnings.filterwarnings("ignore")


In [3]:
df = pd.read_csv(r'./Data/overall_20210524.csv')
df

代號  名稱     年/月  ...  來自營運現金流量成長率  應收帳款週轉次數  存貨週轉率（次）
0      1471  首利  20-Dec  ...    59.047383      0.80      2.41
1      1503  士電  20-Dec  ...   117.784897      1.24      1.36
2      1504  東元  20-Dec  ...     4.224476      1.25      1.01
3      1506  正道  20-Dec  ...   -85.557050      1.09      0.47
4      1507  永大  20-Dec  ...   -10.728787      1.07      0.59
...     ...  ..     ...  ...          ...       ...       ...
18491  8249  菱光  10-Mar  ...     0.000000      1.46      4.36
18492  8261  富鼎  10-Mar  ...     0.000000      0.79      0.83
18493  8374  羅昇  10-Mar  ...     0.000000      1.44      1.39
18494  8996  高力  10-Mar  ...     0.000000      1.32      0.50
18495  9912  偉聯  10-Mar  ...     0.000000      2.43      0.58

[18496 rows x 180 columns]

# Features Selection

In [4]:
# Drop Unused Columns
df.drop(['最高價', '最低價', '成交量(股)', '交易額(萬)', '開盤價', '收盤價', '漲跌幅(%)'], 1, inplace=True)

# Features Selected Manually
cols = ['營收成長率', '營業毛利成長率', '營業利益成長率', '稅前淨利成長率', '經常淨利成長率',
        '折舊性FA成長率', '研究發展費', '每股盈餘', 'ROA(C)稅前息前折舊前', 'ROE(A)－稅後',
        '營業毛利率', '營業利益率', '稅前淨利率', '來自營運之現金流量/營業收入淨額',
        '來自營運之現金流量/ 繼續營業單位損益', '來自營運現金流量成長率', '應收帳款週轉次數',
        '存貨週轉率（次）', '季', '進場訊號']

# Sort Columns
first = ['代號', '名稱', '年份', '年/月']
change_cols = first + [c for c in df.columns if c not in first]
df = df[change_cols]
df.replace({np.inf: 0}, inplace=True)
df.reset_index(inplace=True, drop=True)

# Method A

In [ ]:
# Data Normalization ans Split
df_a = df[first + cols]
X = preprocessing.scale(df_a.iloc[:, 4:-1].values)
y = df_a.iloc[:, -1].values

train_X, test_X, train_y, test_y = model_selection.train_test_split(X, y, test_size = 0.2)

NameError: ignored

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier


param_grid = [ {'n_estimators':[1000],
              'max_depth':[9,50],
              'min_samples_leaf': [50,1000],
              'min_samples_split':[120,500]
         }
]
 
rfc =RandomForestClassifier(random_state=42)
grid_search = GridSearchCV(rfc, param_grid, cv=5,
               scoring='roc_auc')
 
grid_search.fit(train_X, train_y)

grid_search.best_params_

{'max_depth': 50,
 'min_samples_leaf': 50,
 'min_samples_split': 120,
 'n_estimators': 1000}

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
param_grid = {'gamma': [1,0.1,0.01,0.001], 
              }
grid = GridSearchCV(SVC(),param_grid,refit=True,verbose=2)
grid.fit(train_X, train_y)
print(grid.best_estimator_)

Fitting 5 folds for each of 4 candidates, totalling 20 fits
[CV] gamma=1 .........................................................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] .......................................... gamma=1, total=  23.5s
[CV] gamma=1 .........................................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:   23.5s remaining:    0.0s


[CV] .......................................... gamma=1, total=  24.2s
[CV] gamma=1 .........................................................
[CV] .......................................... gamma=1, total=  24.2s
[CV] gamma=1 .........................................................
[CV] .......................................... gamma=1, total=  23.2s
[CV] gamma=1 .........................................................
[CV] .......................................... gamma=1, total=  23.2s
[CV] gamma=0.1 .......................................................
[CV] ........................................ gamma=0.1, total=  25.5s
[CV] gamma=0.1 .......................................................
[CV] ........................................ gamma=0.1, total=  24.4s
[CV] gamma=0.1 .......................................................
[CV] ........................................ gamma=0.1, total=  24.4s
[CV] gamma=0.1 .......................................................
[CV] .

[Parallel(n_jobs=1)]: Done  20 out of  20 | elapsed:  7.7min finished


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=1, kernel='rbf', max_iter=-1,
    probability=False, random_state=None, shrinking=True, tol=0.001,
    verbose=False)


In [ ]:
param_grid = [ {'eta':[0.3, 0.2, 0.1, 0.01],
                'alpha':[0, 1]}]
 
xgb =XGBClassifier()
grid_search = model_selection.GridSearchCV(xgb, param_grid, cv=5,
               scoring='roc_auc')
 
grid_search.fit(train_X, train_y)

grid_search.best_params_

{'alpha': 0, 'eta': 0.3}

In [ ]:
# RF
forest = ensemble.RandomForestClassifier(n_estimators =120,oob_score = True,n_jobs = -1,
                                         max_depth=9,min_samples_split=120,min_samples_leaf=50,
                                         random_state=50) # 調參
forest_fit = forest.fit(train_X, train_y)

# 預測
test_y_predicted = forest.predict(test_X)

# 績效
accuracy = metrics.accuracy_score(test_y, test_y_predicted)
roc = roc_auc_score(test_y, test_y_predicted)
print(accuracy)
print(roc)

metrics.confusion_matrix(test_y, test_y_predicted)

0.7418918918918919
0.5113837558177751


array([[2717,   17],
       [ 938,   28]])

In [ ]:
for i, x in enumerate(df_a.columns[4:-1]):
    print(x, forest.feature_importances_[i])

營業毛利成長率 0.03953806275192244
營業利益成長率 0.061498882222499184
稅前淨利成長率 0.08382443190599384
經常淨利成長率 0.13442484017216585
折舊性FA成長率 0.12059213880271427
研究發展費 0.04192700063430833
每股盈餘 0.030591015828599563
ROA(C)稅前息前折舊前 0.040733197300992674
ROE(A)－稅後 0.04400717861288328
營業毛利率 0.06073077014206644
營業利益率 0.025505861120577185
稅前淨利率 0.029228114536346477
來自營運之現金流量/營業收入淨額 0.03642890307517125
來自營運之現金流量/ 繼續營業單位損益 0.03482330971547541
來自營運現金流量成長率 0.03454926766708073
應收帳款週轉次數 0.029916908435256684
存貨週轉率（次） 0.028204224670170676
季 0.02307741015865722


In [ ]:
# SVM
svc = svm.SVC(kernel='rbf',random_state=1,gamma=0.1,C=1) # 調參
svc_fit = svc.fit(train_X, train_y)

# 預測
test_y_predicted = svc.predict(test_X)

# 績效
accuracy = metrics.accuracy_score(test_y, test_y_predicted)
roc = roc_auc_score(test_y, test_y_predicted)
print(accuracy)
print(roc)

metrics.confusion_matrix(test_y, test_y_predicted)

0.7394594594594595
0.5017046289270456


array([[2732,    2],
       [ 962,    4]])

In [ ]:
# XGBoost
xgb = XGBClassifier(eta=0.3, nthread=-1, alpha=0) # 調參
xgb.fit(train_X, train_y)

# 預測
test_y_predicted = xgb.predict(test_X)

# 績效
accuracy = metrics.accuracy_score(test_y, test_y_predicted)
roc = roc_auc_score(test_y, test_y_predicted)
print(accuracy)
print(roc)

metrics.confusion_matrix(test_y, test_y_predicted)

0.7451351351351352
0.5301033882114964


array([[2678,   60],
       [ 883,   79]])

In [ ]:
df_a['預測結果']  = xgb.predict(X)
df = pd.read_csv(r'/content/drive/MyDrive/機器學習_Final Project_第一組/overall_20210524.csv')
df_a = pd.merge(df_a[['代號', '名稱', '年份', '季'] + ['進場訊號', '預測結果']], df[['代號', '名稱', '年份', '季'] + ['漲跌幅(%)', '開盤價', '收盤價']], on=['代號', '名稱', '年份', '季'], how='left')
df_a.to_csv(r'./Data/Method_A_Final.csv', index=0, header=True, encoding='utf-8')

In [5]:
# Data Normalization ans Split
df_a = df[first + cols]
X = df_a.iloc[:, 4:-1].values
y = df_a.iloc[:, -1].values

train_X, test_X, train_y, test_y = model_selection.train_test_split(X, y, test_size = 0.2)

In [6]:
# Kmeans

for i in range(2, len(cols)):

    kmeans = cluster.KMeans(n_clusters=i)
    k = kmeans.fit_predict(X)
    df_a['Cluster'] = k

    p = 0
    for n, c in df_a['Cluster'].value_counts().items():
        if c <= 1:
            p += 1
        else:
            pass

    if p == 0:
        print(f'=====K : {i}=====')
        for x in list(set(df_a['Cluster'])):
            print(f'Cluster {x}')
            df_ac = df_a[df_a['Cluster']==x]
            df_ac.reset_index(drop=True, inplace=True)
            if len(df_ac['進場訊號'].value_counts()) < 2:
                pass
            else:
                X1 = preprocessing.scale(df_ac.iloc[:, 4:-2].values)
                y1 = df_ac.iloc[:, -2].values
                train_X, test_X, train_y, test_y = model_selection.train_test_split(X1, y1, test_size = 0.2)

                ## RF
                forest = ensemble.RandomForestClassifier(n_estimators=900, oob_score=True, n_jobs=-1,
                        max_depth=9, min_samples_split=120, min_samples_leaf=50,
                                            random_state=50)  # 調參
                forest_fit = forest.fit(train_X, train_y) 
                test_y_predicted = forest.predict(test_X)
                print('/RF/')
                print(f'Accuracy:{metrics.accuracy_score(test_y, test_y_predicted)}')
                print(f'Precision:{metrics.precision_score(test_y, test_y_predicted)}')
                print(f'Recall:{metrics.recall_score(test_y, test_y_predicted)}')
                print(f'F1-Score:{metrics.f1_score(test_y, test_y_predicted)}')
                print(f'混淆矩陣:\n{metrics.confusion_matrix(test_y, test_y_predicted)}\n')

                ## SVM
                svc = svm.SVC(kernel='rbf',random_state=1,gamma=0.1,C=1)  # 調參
                svc_fit = svc.fit(train_X, train_y)
                test_y_predicted = svc.predict(test_X)
                print('/SVM/')
                print(f'Accuracy:{metrics.accuracy_score(test_y, test_y_predicted)}')
                print(f'Precision:{metrics.precision_score(test_y, test_y_predicted)}')
                print(f'Recall:{metrics.recall_score(test_y, test_y_predicted)}')
                print(f'F1-Score:{metrics.f1_score(test_y, test_y_predicted)}')
                print(f'混淆矩陣:\n{metrics.confusion_matrix(test_y, test_y_predicted)}\n')

                ## XGBoost
                xgb = XGBClassifier(eta=0.3, nthread=-1, alpha=1) # 調參
                xgb.fit(train_X, train_y)
                test_y_predicted = xgb.predict(test_X)
                print('/XGBoost/')
                print(f'Accuracy:{metrics.accuracy_score(test_y, test_y_predicted)}')
                print(f'Precision:{metrics.precision_score(test_y, test_y_predicted)}')
                print(f'Recall:{metrics.recall_score(test_y, test_y_predicted)}')
                print(f'F1-Score:{metrics.f1_score(test_y, test_y_predicted)}')
                print(f'混淆矩陣:\n{metrics.confusion_matrix(test_y, test_y_predicted)}\n')

=====K : 2=====
Cluster 0
/RF/
Accuracy:0.7489801468588523
Precision:0.5063291139240507
Recall:0.04329004329004329
F1-Score:0.07976071784646062
混淆矩陣:
[[2714   39]
 [ 884   40]]

/SVM/
Accuracy:0.7487081860212129
Precision:0.5
Recall:0.0010822510822510823
F1-Score:0.002159827213822894
混淆矩陣:
[[2752    1]
 [ 923    1]]

/XGBoost/
Accuracy:0.7519717160728855
Precision:0.5447761194029851
Recall:0.07900432900432901
F1-Score:0.13799621928166353
混淆矩陣:
[[2692   61]
 [ 851   73]]

Cluster 1
/RF/
Accuracy:0.6956521739130435
Precision:0.0
Recall:0.0
F1-Score:0.0
混淆矩陣:
[[16  0]
 [ 7  0]]

/SVM/
Accuracy:0.782608695652174
Precision:0.75
Recall:0.42857142857142855
F1-Score:0.5454545454545454
混淆矩陣:
[[15  1]
 [ 4  3]]

/XGBoost/
Accuracy:0.5217391304347826
Precision:0.25
Recall:0.2857142857142857
F1-Score:0.26666666666666666
混淆矩陣:
[[10  6]
 [ 5  2]]

=====K : 3=====
Cluster 0
/RF/
Accuracy:0.742841100505334
Precision:0.5168539325842697
Recall:0.05005440696409141
F1-Score:0.09126984126984128
混淆矩陣:
[[260

# Best Result

In [ ]:
kmeans = cluster.KMeans(n_clusters=3)
k = kmeans.fit_predict(X)
df_a['Cluster'] = k

In [ ]:
final = pd.DataFrame()
for i in range(0, 3):
    xgb = XGBClassifier(eta=0.3, nthread=-1, alpha=1)
    df_ac = df_a[df_a['Cluster']==i]
    df_ac.reset_index(drop=True, inplace=True)
    if len(df_ac['進場訊號'].value_counts()) < 2:
        df_ac['Cluster'] = df_ac['Cluster'].apply(lambda x:x+1 if x==i else x)
    else:
        X1 = preprocessing.scale(df_ac.iloc[:, 4:-2].values)
        y1 = df_ac.iloc[:, -2].values
        train_X, test_X, train_y, test_y = model_selection.train_test_split(X1, y1, test_size = 0.2)
        xgb.fit(train_X, train_y)
        df_ac['預測結果']  = xgb.predict(X1)
        final = pd.concat([final, df_ac], 0)

In [ ]:
final.預測結果.value_counts()

0    17613
1      883
Name: 預測結果, dtype: int64

In [ ]:
df = pd.read_csv(r'/content/drive/MyDrive/機器學習_Final Project_第一組/overall_20210524.csv')
final = pd.merge(final[['代號', '名稱', '年份', '季'] + ['進場訊號', '預測結果']], df[['代號', '名稱', '年份', '季'] + ['漲跌幅(%)', '開盤價', '收盤價']], on=['代號', '名稱', '年份', '季'], how='left')
final.to_csv(r'./Data/Method_A_Final_Kmeans.csv', index=0, header=True, encoding='utf-8')